### ISSUE TITLE
@ Tools/Design and Experiment: Naive users experienced difficulties in knowing what to do next, from this stage. 

### ISSUE THREAD

**Issue by khoiminhpham** [SAIN-Project/Frontend#1]
From Dr. Kaizman:
"I clicked on Tools | Design and Experiment and it brings up a blank canvas with no obvious means of interaction.  Dead end.  So I went back to watch the video." 

Solution: we can guide naive users through this with more instructional message. I recalled Ahmet placed a similar comment before.

**Comment by Ibrahimvse** [comment]
This issue solved by adding dependency graph of component.  The user can click on (i) button it will show a pop-up layout with two parts . first the details of the component and second he can view the dependency graph of the component that show all components that can be used as an input of this component with exact port that can be connected to this component. It also show all components that can be connected to the output of this component.
