### ISSUE TITLE
Account Page Says Under Development

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#10]
I think we should have some account details showing in that section for each individual user soon.

**Comment by TarandeepSingh562** [comment]
Completed for enhancement.  Full name, email, phone, university, job title, website, bibliography, avatar, and contact button has been added to account page.

**Comment by jgarci40** [comment]
Thanks, @TarandeepSingh562! Thanks as well, @khoiminhpham and @Ibrahimvse! I'm closing this issue.
