### ISSUE TITLE
Rename all instance of "Sain" to "SAIN"

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#12]
This also includes the SAIN logo.

**Comment by khoiminhpham** [comment]
I've changed everything 'Sain' to 'SAIN', Sempai @jgarci40 . Thanks.

**Comment by jgarci40** [comment]
Thanks, @khoiminhpham. @Ibrahimvse @khoiminhpham The tutorials still refer to "Sain" rather than "SAIN".

**Comment by khoiminhpham** [comment]
I just changed that as well, thank you Sempai @jgarci40
