### ISSUE TITLE
Smell Detector Sample Project Seems Incomplete

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#16]
https://www.dropbox.com/s/846y9eo21w30grd/Screen%20Shot%202021-03-08%20at%203.16.55%20PM.png?dl=0

As you can see in the screenshot, the smell detector sample project in the tool integrator seems to be incomplete. The components aren't even connected.

**Comment by Ibrahimvse** [comment]
I could connected them successfully with no issues!

**Comment by jgarci40** [comment]
Since it's a sample project, why are they not already connected?

**Comment by Ibrahimvse** [comment]
because this sample was created long time ago and the blocks data were updated but the changes was not reflected in the old samples. so simply I will remove it and recreate it again

**Comment by Ibrahimvse** [comment]
fixed!
