### ISSUE TITLE
BatchClusteringEngine should not require .mallet or .pipe files in tool integrator

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#19]
BatchClusteringEngine generates topic models without having to take as input an external .mallet or .pipe file, unless you possibly want to create the same topic model for all versions of a system. We should modify the BatchClusteringEngine to support this kind of behavior.

For instance, if you view the main() method of BatchClusteringEngine, you'll see that it only requires three inputs: the directory where each subdirectory is a different version or revision of the system you want to analyze; the directory where all the output will go for every version or revision; and the location of .class files, a jar, or zip (i.e., the binaries).

On the command line, the input to BatchClusteringEngine for Struts would look like this:
`/Users/joshua/source/arcade/subject_systems/Struts2/src out/ lib_struts`

**Comment by khoiminhpham** [comment]
In my experiment, those files existence are required for each output test case Sempai Josh, 
https://photos.app.goo.gl/BUHFDFcXDp2xpGPf8
https://photos.app.goo.gl/83pjxNCGAx7DRprX9
Unless we want to automatically add them to each user's output directory per related experiment they about to perform, but that exceptional process-builder will violate Ibrahim's process-builder auto-generating design.

**Comment by jgarci40** [comment]
Please try the prediction branch of the main arcade repo (not arcadepy). @khoiminhpham

**Comment by Ibrahimvse** [comment]
@jgarci40 BatchClusteringEngine require both mallet and pipe file to be existed inside output folder of BatchClusteringEngine engine and since the user run experiment remotely he don't have ability to write these files in the output directory manually so we automate the process by let the user to upload these files and sain take care of the rest.

**Comment by jgarci40** [comment]
@Ibrahimvse @khoiminhpham It's still way easier for a user to not even have to be aware of mallet or pipe files, and we want to make this process as easy for the user as possible. That's why we should include a version of BatchClusteringEngine that does not require them. We don't have to remove the current BatchClusteringEngine, but we really should add the version that does not require users to provide mallet or pipe files. Did either of you try BatchClusteringEngine from the prediction branch?

**Comment by Ibrahimvse** [comment]
@jgarci40 I dont know and have access to that branch. I just Used the tools that khoi sent it to me. In this case mallet and pipeextracteor should be removed from the tool's list right?

**Comment by jgarci40** [comment]
@Ibrahimvse @khoiminhpham Let's give the BatchClusteringEngine from the prediction branch another name. How about BatchClusteringEngineSimple?

Also, are you sure you can't access this? https://bitbucket.org/joshuaga/arcade/src/prediction/

**Comment by khoiminhpham** [comment]
I tried in prediction branch Sempai @jgarci40, still have that hard coded output.pipe and infer.mallet files path requirement issue. 
https://photos.app.goo.gl/nNp4SNjoii3qci5n7

Or would you like us to change Arcade's source code to solve that issue, cause that may sound simpler than to be solved from SAIN engine source code.

**Comment by jgarci40** [comment]
@khoiminhpham You're definitely not using the prediction branch.

**Comment by khoiminhpham** [comment]
Sempai @jgarci40 , I retried it several times, still got the same scenario 
https://photos.app.goo.gl/aLBn3fZYJfGYGv2R6

I git clone from "https://bitbucket.org/joshuaga/arcade/src/prediction/", and use "edu.usc.softarch.arcade.clustering.BatchClusteringEngine.java", Am I possibly missing anything :(

**Comment by khoiminhpham** [comment]
I've added BatchClusteringEngineSimple component. everything seems to work now except the same Cross-Origin-Request-Block issue Ibrahim is dealing - which we will deal with independently.

https://photos.app.goo.gl/BgxdHHkF9Ajj7Spy7

**Comment by jgarci40** [comment]
Thanks, @khoiminhpham!

**Comment by khoiminhpham** [comment]
This is solved Sempai @jgarci40, now we have BatchClusteringEngineSimple. Thanks.

**Comment by TarandeepSingh562** [comment]
BatchClusteringEngineSimple seems to be added and functioning as intended through the main website. I had no issues when running the tool multiple times.

**Comment by Ibrahimvse** [comment]
solved
