### ISSUE TITLE
@ Tools/Tool menu: Check box doesn't do anything.

### ISSUE THREAD

**Issue by khoiminhpham** [SAIN-Project/Frontend#2]
From Dr. Kaizman:
"I tried out the Tools | Tools menu item.  It brings up a list of tools, programming languages, etc.  I click on checkboxes and nothing happens." 

Solution: This is supposed to be a filter for components list, currently our tool components dataset is empty, we will have further update on this.

**Comment by Ibrahimvse** [comment]
We are Modifying tool schema in the database (adding more details when uploading new tool). that bug will be fixed after finishing this part and update the database to match the new schema since the current schema has only basic information we need to add more information about tools.

**Comment by Ibrahimvse** [comment]
Solved
