### ISSUE TITLE
SAIN DependencyBuilderJava Access Denied

### ISSUE THREAD

**Issue by YuqiHuai** [SAIN-Project/Frontend#23]
I included screenshot and the setup.
<img width="393" alt="Screen Shot 2021-03-17 at 4 40 26 PM" src="https://user-images.githubusercontent.com/34195403/111438880-bf790180-873f-11eb-8a64-b12029f7dc95.png">
<img width="921" alt="Screen Shot 2021-03-17 at 4 40 38 PM" src="https://user-images.githubusercontent.com/34195403/111438885-c142c500-873f-11eb-985a-a005242e2168.png">
<img width="989" alt="Screen Shot 2021-03-17 at 4 40 18 PM" src="https://user-images.githubusercontent.com/34195403/111438877-be47d480-873f-11eb-9a83-d294f17f46d3.png">

This issue did not occur earlier last week, but it it looks like DependencyBuilderJava is not able to access output file.

**Comment by jgarci40** [comment]
Hi @YuqiHuai. I think it would help if you could provide the developers access to your CalculatorExample.zip file.

**Comment by YuqiHuai** [comment]
[CalculatorExample.zip](https://github.com/SAIN-Project/Frontend/files/6168815/CalculatorExample.zip)
This is a zip file that does not work

[build.zip](https://github.com/SAIN-Project/Frontend/files/6168818/build.zip)
here is another zip that worked before but stopped working. Dependency builder does not seem to execute anything

**Comment by khoiminhpham** [comment]
Thank you for your notification @YuqiHuai , that was my mistake, last time I fixed email verification feature, I forgot to re-run the server "as Administrators". that's where your error "access denied" came from.  

It should be working properly now, please give it another try as your convenience. 
https://photos.app.goo.gl/j6FDQw7Wq3P87YRz9

That CalculatorExample project looks interesting btw. Thanks.

**Comment by jgarci40** [comment]
@YuqiHuai Can you please try these inputs again when you get a chance?

**Comment by YuqiHuai** [comment]
Issue fix confirmed!
