### ISSUE TITLE
Dependency Builder Java - No working SAIN datasets

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#24]
There appear to be no datasets in SAIN that can be readily used with the Dependency Builder Java using the feature that allows you to load datasets from the SAIN repository.

**Comment by khoiminhpham** [comment]
You're right Sempai Josh, I just added it here, it's working fine now. Thanks,

https://photos.app.goo.gl/n4XZtgM8uFmsV8Qh8

**Comment by khoiminhpham** [comment]
This is solved Sempai @jgarci40  , now it will be auto loaded in ready-to-run experiment (Smell Detector running with mage 1.4.45), we can download it from dataset tab.

**Comment by TarandeepSingh562** [comment]
The bug seems to be solved. Ran the ready-to-run experiment a couple of times with no errors and it took about 30 seconds each time to download from the dataset tab.

**Comment by jgarci40** [comment]
Thanks, @TarandeepSingh562 and @khoiminhpham. Closing this issue...
