### ISSUE TITLE
BatchClusteringEngineSimple does not work with the struts.zip dataset

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#25]
Please see the subject line.

**Comment by khoiminhpham** [comment]
I tried with the struts.zip, it seems to be working fine Sempai, it took very long time to finish (around 20 mins)

https://photos.app.goo.gl/u4tkJfh8aTTxod8UA

**Comment by khoiminhpham** [comment]
This is solved Sempai @jgarci40 , you can quickly re-try it in ready-to-run experiment (BatchClusteringEngine running on struts (2.3.30)).

**Comment by TarandeepSingh562** [comment]
This may not be completely fixed yet. I ran it through "Ready to Run Experiments Samples" multiple times, and I received an error each time: "process SmellEvolutionAnalyzer exited with error::undefined". I've also attached an image to display the error I'm receiving.
![image](https://user-images.githubusercontent.com/85138366/134440120-88395bfe-cf2f-44d0-90c7-967f2cc99071.png)

**Comment by jgarci40** [comment]
@khoiminhpham, would you be able to look at this please?

**Comment by TarandeepSingh562** [comment]
BatchClusteringEngineSimple seems to be working fine with the struts.zip dataset now. The run time was around 3 minutes, and I received no more errors.

![image](https://user-images.githubusercontent.com/85138366/154162995-d58973d1-1568-4496-a304-522a8465b6d7.png)

**Comment by jgarci40** [comment]
Thanks, @khoiminhpham @TarandeepSingh562 ! Closing this issue.
