### ISSUE TITLE
BatchClusteringEngineSimple asks for a classpath, but it doesn’t need one

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#26]
Please see the subject line.

**Comment by khoiminhpham** [comment]
From prediction branch we opened last time, classpath seems to be among the required passing arguments Sempai, I'm curious about this situation as well.
https://photos.app.goo.gl/fGxMdoAQpf8aMowq5

**Comment by khoiminhpham** [comment]
This is solved Sempai @jgarci40, this component starts with classcycle (JavaDepsBuilder) to extract dependencies, classpath is required by classcycle.
