### ISSUE TITLE
Components' names: unclear, need to be renamed

### ISSUE THREAD

**Issue by khoiminhpham** [SAIN-Project/Frontend#3]
From Mehdi:
"Right now the components are organized based on the parent tool, but we need to organize them based on their core functionality (Reverse Engineering, Analysis, Fact Extractor, etc.). 
Also the naming are not very informative (eg. AcdcWithSmellDetection, or BatchEvoSystem, ACDC)."

Solutions: We're collecting naming ideas here, if you have any good name for any component available in SAIN, please help us improve. Thanks.

**Comment by Ibrahimvse** [comment]
Solved, the names are now as an author suggest
