### ISSUE TITLE
Anyone should be able to visit the About SAIN page without logging in

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#31]
The About SAIN page at http://sain.usc.edu/aboutsain should be viewable by anyone without logging in.

**Comment by khoiminhpham** [comment]
I remember many months ago, we've fixed this, tested and closed the case properly (⇀‸↼‶)
Anyway I just fixed it again, and push commit to github, hopefully this issue won't appear again. 
Please feel free to give it another try Sempai @jgarci40, and thank you for all the testing efforts.

**Comment by jgarci40** [comment]
Works for me now. Thanks a lot for the quick response and fix, Khoi!
