### ISSUE TITLE
"SmellAnalyzer" component not functioning

### ISSUE THREAD

**Issue by Sanshin-SF** [SAIN-Project/Frontend#32]
While attempting to replicate the results on[ this paper](https://jgarcia.ics.uci.edu/wp-content/uploads/ICSA_2021___SAIN_Paper-20.pdf), I ran into a problem with the component "SmellAnalyzer" under "Utilities".

"SmellAnalyzer" would refuse to run and It just returns a message "undefined".
Please look at the short video for more details.

https://user-images.githubusercontent.com/76271316/131193498-6d10e792-e4ee-4ab4-9753-a3dca95432eb.mp4

**Comment by khoiminhpham** [comment]
Thanks for reporting an issue, it should be working now, please feel free to give it another try.

![image](https://user-images.githubusercontent.com/47465932/131213356-c2cb2aa4-93a2-491a-9f3e-ea62ec5044aa.png)

**Comment by Sanshin-SF** [comment]
Thank you for your quick repair.
I have tried it and it does indeed work.
