### ISSUE TITLE
Rename of "Sain Faqs"

### ISSUE THREAD

**Issue by TarandeepSingh562** [SAIN-Project/Frontend#34]
I believe "Sain Faqs" should be renamed to "SAIN FAQ".

![image](https://user-images.githubusercontent.com/85138366/133153686-f6f66150-77e8-4111-9dd0-3092974aa03f.png)

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this, guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
fixed
