### ISSUE TITLE
Connection Error to SAIN's Main Website

### ISSUE THREAD

**Issue by TarandeepSingh562** [SAIN-Project/Frontend#35]
When attempting to replicate/test [issue30](https://github.com/SAIN-Project/Frontend/issues/30), I ran into some connection errors to the main website. This error seems to be IP related since I can't connect to the main website from all my computers (tried 3 different computers). I have attached images of the error in the chat below.

![image](https://user-images.githubusercontent.com/85138366/134987678-cde54afd-8b3b-45f4-8e8b-4cfbe5192a14.png)
![image](https://user-images.githubusercontent.com/85138366/134987718-9a689fb0-af9d-48a6-a5c3-16832e4c0bf7.png)

**Comment by jgarci40** [comment]
Hi @Ibrahimvse and @khoiminhpham. Could you both please look into this?

**Comment by TarandeepSingh562** [comment]
Alongside issue https://github.com/SAIN-Project/Frontend/issues/30, this issue also seems to be solved. The main website (http://www.sain.info/aboutsain) seems to be working as intended.

**Comment by jgarci40** [comment]
Thanks, @TarandeepSingh562 , @Ibrahimvse , @khoiminhpham 
Closing...
