### ISSUE TITLE
Fix the magnifier tool

### ISSUE THREAD

**Issue by mfazelnia** [SAIN-Project/Frontend#39]
The magnifier on the tool integration page does not work correctly.

**Comment by jgarci40** [comment]
@mfazelnia, could you please elaborate?

**Comment by jgarci40** [comment]
OK, instead of zooming, it scrolls...

**Comment by TarandeepSingh562** [comment]
This issue is solved. The magnifier tool on the 'Tool Integration' tab is working correctly now. It zooms in/out instead of scrolling.

**Comment by jgarci40** [comment]
Thanks, @TarandeepSingh562 ! Closing.
