### ISSUE TITLE
Sharing the status of a process with users

### ISSUE THREAD

**Issue by aokutan** [SAIN-Project/Frontend#4]
When an experiment is run, the system should inform the user about each step/stage completed, and the overall progress/status of the back-end processes. When a component is done or in case of any type of error, the user should be informed. When the process is done, the user should be notified about where he/she can find the output generated. The colors of the components could be changed depending on the status of the corresponding back end process. Different color codes could be used for different cases like "In progress", "Error", "Warning" or "Completed successfully".

**Comment by Ibrahimvse** [comment]
done!
