### ISSUE TITLE
Time Selector Format Error

### ISSUE THREAD

**Issue by Codegass** [SAIN-Project/Frontend#41]
The time selector in the components (like HSDM and Bug Space) will follow the local computer setting's format.
For example: my computer is year-month-date.
This format will be kept in the final command when running the script.
So this raises the issue as followed: 
```
Error in parsing time: 2000-01-01 in edu.drexe.cs.rise.DesignSpace.util.DateFormat
Error in parsing time: 2015-01-01 in edu.drexe.cs.rise.DesignSpace.util.DateFormat
```
Because the default parser for the date time in all the scripts are date-month-year.

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this one guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
could not replicate the issue. every thing work fine
![image](https://user-images.githubusercontent.com/62664749/160951504-c228907a-527a-431c-94d6-d41263ab9b09.png)

![image](https://user-images.githubusercontent.com/62664749/160951614-19237978-57c7-471d-85ba-d9a8326c9131.png)

**Comment by khoiminhpham** [comment]
I fixed this in one occasion, just a different date time format between angular form and SDSM input.
