### ISSUE TITLE
'SAIN Faqs' Link Issues

### ISSUE THREAD

**Issue by TarandeepSingh562** [SAIN-Project/Frontend#42]
The links listed below 'Sain Frequently Asked Questions' are not accessible and need updating. Also, as a suggestion, these links might be better as hyperlinks for a better/easier experience. I've shown an example of one of the links that does not work down below. Thanks.

![image](https://user-images.githubusercontent.com/85138366/147142536-09bcfcf8-8af3-47cb-8596-48b6136a0f1e.png)

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this, guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
fixed
