### ISSUE TITLE
Parsing time error

### ISSUE THREAD

**Issue by a-shokri** [SAIN-Project/Frontend#43]
When I run the tool integration, I receive the following error:
Error in parsing time: 2000-01-01 in edu.drexe.cs.rise.DesignSpace.util.DateFormat

Reproducibility: I put 01/01/2000 as start date for Bug Space component. It seems that the same exception has been thrown for all the date fields I filled out in Hdsm and Bug Space tools.

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this one, guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
Could not replicate the error. The date is entered with date packer so no error suppose to be produced!

**Comment by khoiminhpham** [comment]
same thing with issue $41 - solved
