### ISSUE TITLE
Error pulling docker image

### ISSUE THREAD

**Issue by rsatrioadi** [SAIN-Project/Frontend#48]
I tried to do a `docker run -d -p 80:80 ibrahimidn/sain:latest` and got `Error response from daemon: manifest for ibrahimidn/sain:latest not found: manifest unknown: manifest unknown`.

**Comment by jgarci40** [comment]
@Ibrahimvse @khoiminhpham Hi guys, can I please get a status update on this?

**Comment by khoiminhpham** [comment]
I've never tried this feature Sempai Josh. 
@Ibrahimvse can you please have a look at this issue. Thanks

**Comment by jgarci40** [comment]
Hi @Ibrahimvse ,

Sunny Wong, Yuanfang's first, or at least an early, graduated Ph.D. student, tried the updates to the Docker Container and wasn't able to get it to fully work:

> Good news:
> I was able to pull the Docker image and run it (per the tutorial on the website).
>
> Bad news:
> I can't find a tutorial on how to actually use it from the Docker container. If I go to http://localhost:8080/ then it just gives me a API response saying that it's "runing" but I don't know what URL to access a UI.
> I went poking around inside the container to try to find a URL to something. I put in a URL that I found and the Docker container crashed, trying to reach out to an IP address belonging to RIT

Can you please look into this?

Thanks,
Josh

**Comment by Ibrahimvse** [comment]
Hi Sunny, 

The Sain Docker Container is only for backend so you still need the sain front end "www.sain.info" to run your experiments on your local docker container of sain . To run Docker you need to go to Tools->Tool Integration->Server-> local and specify the port and click on connect.
![image](https://user-images.githubusercontent.com/62664749/160950508-2e979253-a4ae-4ba1-99dc-79a15cb09a65.png)
