### ISSUE TITLE
Saving Workflows and Sharing within SAIN

### ISSUE THREAD

**Issue by TarandeepSingh562** [SAIN-Project/Frontend#49]
Hi,

This post is to keep track of a feature that is currently being worked on/finalized, which is the saving of workflows and the ability to share them with other SAIN users.  Within SAIN's tool integration page, there is a way to save workflows, however, I believe there is not a way to share them with other SAN users yet. 

The first part works well as shown in images down below. 
![image](https://user-images.githubusercontent.com/85138366/155626498-fcee79b2-ffd6-471c-9739-4b279deb44b8.png)

Workflow 1 has been added successfully as shown on the bottom of this screenshot. 
![image](https://user-images.githubusercontent.com/85138366/155626986-88b6f80a-7124-49e8-947b-dd34bca3c172.png)

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse Hi Guys. Is there a way to share user-created workflows between users from within SAIN yet? If not, are either of you guys working on it?

@TarandeepSingh562 I'm tagging you to make sure you are kept updated on this issue.

**Comment by khoiminhpham** [comment]
Hi team,

The "save ready-to-run sample" will make it available for everybody to try it in "ready-to-run sample" list, you (or other users) can simply open the sample you recently saved and run it.

Thanks,

**Comment by jgarci40** [comment]
Thanks for the info, @khoiminhpham. @TarandeepSingh562, could you please try out those two features together?

**Comment by TarandeepSingh562** [comment]
> 

Thanks for the clarification @khoiminhpham. Yes, in this case, both features are working correctly as intended.

**Comment by jgarci40** [comment]
Thanks, @TarandeepSingh562 and @khoiminhpham. I'm closing this issue.
