### ISSUE TITLE
Dependency Builder for Java in the Tool Integrator has a different name than on the SAIN Tools page

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#5]
https://www.dropbox.com/s/1jt6q1ud59vwu6j/Screen%20Shot%202020-11-09%20at%202.29.16%20PM.png?dl=0
says "Dependency Builder Java"

http://sain.usc.edu/tools/componentdetails/5f806d25a948c12fd0198b77
says "JavaDepsBuilder"

**Comment by Ibrahimvse** [comment]
solved
