### ISSUE TITLE
Add tool(s) to SAIN that makes source work with Dependency Builder and BatchClusteringEngine*

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#50]

**Comment by Ibrahimvse** [comment]
They already added!!
![image](https://user-images.githubusercontent.com/62664749/160951775-63d68c87-dd1f-45f2-8a71-80c96e5462c4.png)

![image](https://user-images.githubusercontent.com/62664749/160951912-f604e878-e6f7-45a4-a73d-e5d528bab153.png)
