### ISSUE TITLE
Mage and Struts

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#52]
Hi @khoiminhpham and @Ibrahimvse,

A couple of issues we noticed in preparation for the SAIN School next week:
1. The Mage dataset is not available to choose from on SAIN. It's not on the pages where you can browse or search for datasets, and it's thus not selectable from Tool Integration.
2. I tried to recreate the ready-to-run Mage experiment, except with Struts instead of Mage, but there is an error that occurs when I try to do so. I've created the failing experiment as a ready-to-run experiment in SAIN called "struts acdc+smell detection".

Could you guys please take a look into this and fix it ASAP? This part will be used by Mehdi for walking through the SAIN functions and having participants try them out.

Thanks,
Josh

**Comment by Ibrahimvse** [comment]
Hi Joshua,
I reuploaded mage project to the datasets.
The second point you selected struts which is multiple versions of struts project. The Dependency builder tool work only on single project so you need to select struts-2.5.8.zip from that dataset. If you want to run multiple versions you need to use AcdcWithSmellDetection which is alternative of all those three tools( dependency builder,acdc, and smellDetection) but work on multiple versions.
