### ISSUE TITLE
Dependency Builder for Java in Tool Integrator throws a InvocationTargetException

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#6]
https://www.dropbox.com/s/svsqj7jgzcgn7qx/struts-2.3.30.zip?dl=0

![Screen Shot 2020-11-09 at 2 27 02 PM](https://user-images.githubusercontent.com/8866794/98604461-8e238d00-2298-11eb-8412-130f0cae0bc4.png)

**Comment by khoiminhpham** [comment]
class path should start from root folder Sempai @jgarci40 . 
In your case it should be: "struts-2.3.30/lib_struts"
I retried and it worked properly:
https://photos.app.goo.gl/cwAi4YW3R8Zkmcqb9

If it also works for you now, can you please close this ticket issue, thanks.

**Comment by jgarci40** [comment]
Thanks, @khoiminhpham!
