### ISSUE TITLE
BatchClusteringEngine should not require pipe or mallet files as input

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#7]
The following error message pops up:

https://www.dropbox.com/s/n45vgvboilfqy77/Screen%20Shot%202020-11-09%20at%203.00.53%20PM.png?dl=0

In fact, the pipe files should not be an input to BatchClusteringEngine. The ARCADE manual should be updated accordingly.

**Comment by Ibrahimvse** [comment]
solved, They are implicitly required. The Batch Clustering Engine required mallet file and pipe file to be exist inside 'base' directory inside output directory of batch clustering engine
